### PR TITLE
made it smaller

### PR DESCRIPTION
**Pull request by wxnnvs**
im sorry for the formatting, my vs code did a tab less everywhere

### CODE REVIEW

**Comment by radmanplays** [comment]
can you open a terminal in vs code and do "npm run build" then commit the changes?

**Comment by wxnnvs** [comment]
Kk

**Comment by wxnnvs** [comment]
image
it doesn't work

**Comment by wxnnvs** [comment]
nvm, its my problem

**Comment by wxnnvs** [comment]
i built it @radmanplays 
idk what it means with the conflicting thingy

**Comment by wxnnvs** [comment]
don't merge it
it's broken :_(

**Comment by leahanderson1** [comment]
> can you open a terminal in vs code and do "npm run build" then commit the changes?

the workflow i made automatically does this

**Pull request merged**
